name: SonarQube Code Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip -d $HOME
          export PATH="$HOME/sonar-scanner-5.0.1.3006-linux/bin:$PATH"

      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          $HOME/sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner \
            -Dsonar.host.url=http://docker-test-alb-10113341.ap-northeast-2.elb.amazonaws.com:9000 \
            -Dsonar.login=$SONAR_TOKEN

